config/routes.rb
App::Application.routes.draw do

  resources :classifications

  resources :inventories

  resources :assets

  resources :analyses

  resources :labellings

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :asset_custodian, :asset_name, :at_origin, :availability, :classification, :data_retention_period, :des_asset, :info_moved_des, :integrity, :op_function, :personal_data, :personal_sensitive_data, :pro_name, :pro_owner, :sensitive_customer_data, :type_asset
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventories }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory }
      format.pdf do
        pdf = InventoriesPdf.new(@inventory)
        send_data pdf.render , filename: "#{@inventory.op_function}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /inventories/new
  # GET /inventories/new.json
  def new
    @inventory = Inventory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory }
    end
  end

  # GET /inventories/1/edit
  def edit
    @inventory = Inventory.find(params[:id])
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(params[:inventory])

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render json: @inventory, status: :created, location: @inventory }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventories/1
  # PUT /inventories/1.json
  def update
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      if @inventory.update_attributes(params[:inventory])
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span11 offset well">
  <div class="form-horizontal">
    <div class="accordion " id="accordion2">
      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            New Asset 
          </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse in">
          <div class="accordion-inner">
            <div class="control-group">
              <%= f.label "Operating Unit / function" %><br />
              <%= f.text_field :op_function %>
            </div>
            <div class="control-group">
              <%= f.label "process name" %><br />
              <%= f.text_field :pro_name %>
            </div>
            <div class="control-group">
              <%= f.label "process owner" %><br />
              <%= f.text_field :pro_owner %>
            </div>
            <div class="control-group">
              <%= f.label "asset of name" %><br />
              <%= f.text_field :asset_name %>
            </div>  
            <div class="control-group">
              <%= f.label "description of asset" %><br />
              <%= f.text_field :des_asset %>
            </div> 
            <div class="control-group">
              <%= f.label "type of information asset" %><br />
              <%= f.text_field :type_asset %>
            </div> 
            <div class="control-group">
              <%= f.label "personal data" %><br />
              <%=f.radio_button :personal_data, 'Yes' %><%= f.label 'Yes' %>
              <%=f.radio_button :personal_data, 'No' %><%= f.label 'No' %>
            </div> 
            <div class="control-group">
              <%= f.label "personal sensitive data" %><br />              
              <%=f.radio_button :personal_sensitive_data, 'Yes' %><%= f.label 'Yes' %>
              <%=f.radio_button :personal_sensitive_data, 'No' %><%= f.label 'No' %>
            </div>
            <div class="control-group">
              <%= f.label "sensitive customer data" %><br />              
              <%=f.radio_button :sensitive_customer_data, 'Yes' %><%= f.label 'Yes' %>
              <%=f.radio_button :sensitive_customer_data, 'No' %><%= f.label 'No' %>
            </div>
            <div class="control-group">
              <%= f.label "classification" %><br />
              <%= f.text_field :classification %>
            </div>
            <div class="control-group">
              <%= f.label "integrity" %><br />
              <%= f.text_field :integrity %>
            </div>
            <div class="control-group">
              <%= f.label "availability" %><br />
              <%= f.text_field :availability %>
            </div>
            <div class="control-group">
              <%= f.label "asset custodian" %><br />
              <%= f.text_field :asset_custodian %>
            </div>
            <div class="control-group">
              <%= f.label "data retention period" %><br />
              <%= f.text_field :data_retention_period %>
            </div>
            <div class="control-group">
              <%= f.label "at origin" %><br />
              <%= f.text_field :at_origin %>
            </div>
            <div class="control-group">
              <%= f.label "information is moved" %><br />
              <%= f.text_field :info_moved_des %>
            </div>

          </div>
        </div>
      </div>      
    </div>
  </div>
  <br>
  <div>
    <%= f.submit 'Create Asset', :class =>  "pure-button pure-button-primary"%>
    <%= link_to 'Cancel', policies_path , :class => "pure-button pure-button-primary"%>
  </div>
  <% end %>
</div>

app/views/inventories/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well"> 
				<h1>Editing Asset</h1>

				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/inventories/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Asset</a></li>
                        <li><a href="#EP" data-toggle="tab">Existing Asset</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">
                            <table class="table table-bordered">
                                <tr>
    <th>Operating Unit / function</th>
    <th>Process name</th>
    <th>Process owner</th>
    <th>Asset name</th>    
    <th>Classification</th>
    <th>Integrity</th>
    <th>Availability</th>    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventories.each do |inventory| %>
  <tr>
    <td><%= inventory.op_function %></td>
    <td><%= inventory.pro_name %></td>
    <td><%= inventory.pro_owner %></td>
    <td><%= inventory.asset_name %></td>    
    <td><%= inventory.classification %></td>
    <td><%= inventory.integrity %></td>
    <td><%= inventory.availability %></td>    
    <td><%= link_to 'Show', inventory %></td>
    <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
    <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
                        <br />
                        <%= link_to 'New Inventory', new_inventory_path , :class => "pure-button pure-button-primary" %>
                    </div>
                    <div id="EP" class="tab-pane">
                        <h4>Existing Asset</h4>
                        <p> Coming Soon ...</p>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/inventories/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
		<div><img src="/images/fixnix.png"></div>
	</div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/inventories/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

      <p>
  <b>Operating unit / function:</b>
  <%= @inventory.op_function %>
</p>

<p>
  <b>Process name:</b>
  <%= @inventory.pro_name %>
</p>

<p>
  <b>Process owner:</b>
  <%= @inventory.pro_owner %>
</p>

<p>
  <b>Asset name:</b>
  <%= @inventory.asset_name %>
</p>

<p>
  <b>Description asset:</b>
  <%= @inventory.des_asset %>
</p>

<p>
  <b>Type asset:</b>
  <%= @inventory.type_asset %>
</p>

<p>
  <b>Personal data:</b>
  <%= @inventory.personal_data %>
</p>

<p>
  <b>Personal sensitive data:</b>
  <%= @inventory.personal_sensitive_data %>
</p>

<p>
  <b>Sensitive customer data:</b>
  <%= @inventory.sensitive_customer_data %>
</p>

<p>
  <b>Classification:</b>
  <%= @inventory.classification %>
</p>

<p>
  <b>Integrity:</b>
  <%= @inventory.integrity %>
</p>

<p>
  <b>Availability:</b>
  <%= @inventory.availability %>
</p>

<p>
  <b>Asset custodian:</b>
  <%= @inventory.asset_custodian %>
</p>

<p>
  <b>Data retention period:</b>
  <%= @inventory.data_retention_period %>
</p>

<p>
  <b>At origin:</b>
  <%= @inventory.at_origin %>
</p>

<p>
  <b>Information is moved:</b>
  <%= @inventory.info_moved_des %>
</p>

       <%= link_to "Create PDF", inventory_path(@inventory, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
       <%= link_to 'Edit', edit_inventory_path(@inventory) , :class => "pure-button pure-button-primary"  %> 
       <%= link_to 'New Asset', new_inventory_path , :class => "pure-button pure-button-primary"  %>

     </div>
   </div>
   <!--   <div id="footer">Footer</div> -->

 </body>
 </html>