config/routes.rb
App::Application.routes.draw do

  resources :classifications

  resources :inventories

  resources :assets

  resources :analyses

  resources :labellings

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/labelling.rb
class Labelling < ActiveRecord::Base
  attr_accessible :criteria, :name
  has_many :assets
end

app/controllers/labellings_controller.rb
class LabellingsController < ApplicationController
  # GET /labellings
  # GET /labellings.json
  def index
    @labellings = Labelling.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labellings }
    end
  end

  # GET /labellings/1
  # GET /labellings/1.json
  def show
    @labelling = Labelling.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @labelling }
      format.pdf do
        pdf = LabellingsPdf.new(@labelling)
        send_data pdf.render , filename: "#{@labelling.name}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /labellings/new
  # GET /labellings/new.json
  def new
    @labelling = Labelling.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @labelling }
    end
  end

  # GET /labellings/1/edit
  def edit
    @labelling = Labelling.find(params[:id])
  end

  # POST /labellings
  # POST /labellings.json
  def create
    @labelling = Labelling.new(params[:labelling])

    respond_to do |format|
      if @labelling.save
        format.html { redirect_to @labelling, notice: 'Labelling was successfully created.' }
        format.json { render json: @labelling, status: :created, location: @labelling }
      else
        format.html { render action: "new" }
        format.json { render json: @labelling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labellings/1
  # PUT /labellings/1.json
  def update
    @labelling = Labelling.find(params[:id])

    respond_to do |format|
      if @labelling.update_attributes(params[:labelling])
        format.html { redirect_to @labelling, notice: 'Labelling was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @labelling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labellings/1
  # DELETE /labellings/1.json
  def destroy
    @labelling = Labelling.find(params[:id])
    @labelling.destroy

    respond_to do |format|
      format.html { redirect_to labellings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/labellings_helper.rb
module LabellingsHelper
end

app/views/labellings/_form.html.erb
<%= form_for(@labelling) do |f| %>
  <% if @labelling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@labelling.errors.count, "error") %> prohibited this labelling from being saved:</h2>

      <ul>
      <% @labelling.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  


<div class="span11 offset well">
  <div class="form-horizontal">

    <div class="control-group">
      <%= f.label :name %><br />
    <%= f.text_field :name %><br>
    You will need to create a name for your classification. Examples could be "Confidential", "Classified", etc. 
    </div>
    <div class="control-group">
       <%= f.label :criteria %><br />
    <%= f.text_field :criteria %><br>
    Very important. It's crucial when classifying to be consistent with the criteria you use to say a given risk is one or another type. Ideally your criteria should be simple and practical. I wouldnt get too creative here.
    </div>
   
    
    
    
    
    <div class="control-group">
      <%= f.submit 'Create Label', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', labellings_path , :class => "pure-button pure-button-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/labellings/edit.html.erb
<!-- <h1>Editing labelling</h1>

<%= render 'form' %>

<%= link_to 'Show', @labelling %> |
<%= link_to 'Back', labellings_path %> -->


<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/labellings/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Asset Labeling</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">

                            <table class="table table-bordered">
                              <tr>                                
                                <th>Name</th>
                                <th>Classification Criteria</th>
                            </tr>

                            <% @labellings.each do |labelling| %>
                            <tr>
                                <td><%= labelling.name %></td>
                                <td><%= labelling.criteria %></td>
                                <td><%= link_to 'Show', labelling %></td>
                                <td><%= link_to 'Edit', edit_labelling_path(labelling) %></td>
                                <td><%= link_to 'Destroy', labelling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                </tr>
                                <% end %>
                            </table>

                        <br />

                        <%= link_to 'New Labelling', new_labelling_path, :class => "pure-button pure-button-primary"  %>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/labellings/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/labellings/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

     <p>
  <b>Name:</b>
  <%= @labelling.name %>
</p>

<p>
  <b>Criteria:</b>
  <%= @labelling.criteria %>
</p>


      <%= link_to "Create PDF", labelling_path(@labelling, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_labelling_path(@labelling) , :class => "pure-button pure-button-primary" %> 
      

      <%= link_to 'New Asset Type', new_labelling_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>