config/routes.rb
App::Application.routes.draw do

  resources :classifications

  resources :inventories

  resources :assets

  resources :analyses

  resources :labellings

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/businessunit.rb
class Businessunit < ActiveRecord::Base
  attr_accessible :b_area, :b_city, :b_country, :b_name, :b_site, :b_state ,:time_zone
  has_many :assets   
end

app/controllers/businessunits_controller.rb
class BusinessunitsController < ApplicationController
  # GET /businessunits
  # GET /businessunits.json
  def index
    @businessunits = Businessunit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @businessunits }
    end
  end

  # GET /businessunits/1
  # GET /businessunits/1.json
  def show
    @businessunit = Businessunit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @businessunit }
      format.pdf do
        pdf = BusinessunitsPdf.new(@businessunit)
        send_data pdf.render , filename: "#{@businessunit.b_name}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /businessunits/new
  # GET /businessunits/new.json
  def new
    @businessunit = Businessunit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @businessunit }
    end
  end

  # GET /businessunits/1/edit
  def edit
    @businessunit = Businessunit.find(params[:id])
  end

  # POST /businessunits
  # POST /businessunits.json
  def create
    @businessunit = Businessunit.new(params[:businessunit])

    respond_to do |format|
      if @businessunit.save
        format.html { redirect_to @businessunit, notice: 'Businessunit was successfully created.' }
        format.json { render json: @businessunit, status: :created, location: @businessunit }
      else
        format.html { render action: "new" }
        format.json { render json: @businessunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businessunits/1
  # PUT /businessunits/1.json
  def update
    @businessunit = Businessunit.find(params[:id])

    respond_to do |format|
      if @businessunit.update_attributes(params[:businessunit])
        format.html { redirect_to @businessunit, notice: 'Businessunit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @businessunit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businessunits/1
  # DELETE /businessunits/1.json
  def destroy
    @businessunit = Businessunit.find(params[:id])
    @businessunit.destroy

    respond_to do |format|
      format.html { redirect_to businessunits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/businessunits_helper.rb
module BusinessunitsHelper
end

app/views/businessunits/_form.html.erb
<%= form_for(@businessunit) do |f| %>
<% if @businessunit.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@businessunit.errors.count, "error") %> prohibited this businessunit from being saved:</h2>

  <ul>
    <% @businessunit.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="span11 offset well">
  <div class="form-horizontal">

    <div class="control-group">
      <%= f.label "Classification Type" %>
      <%= f.text_field :b_name %><br>
      name a new type
    </div>
    <div class="control-group">
      <%= f.label "Name" %>
      <%= f.text_field :b_site %><br>
      You will need to create a name for your classification. Examples could be "High", "Low", etc.
    </div>
    <div class="control-group">
      <%= f.label "Type" %>
      <%= f.text_field :b_area %><br>
      Type of an asset. Examples: "Hardware, Software, Etc"
    </div>
    <div class="control-group">
      <%= f.label "Classification Criteria" %>
      <%= f.text_field :b_city %><br>
      Very important. It's crucial when classifying to be consistent with the criteria you use to say a given asset is one or another type. Ideally your criteria should be simple and practical. Dont get too creative here. Examples: "The asset worth is higher than a 40k EUR", "The disclosure of this asset could mean legal actions against the company", Etc.
    </div>
    <div class="control-group">
      <%= f.label "Value" %>
      <%= f.text_field :b_state %><br>
      At a later stage of your classification (and Risk Management) this will be useful to give numerical priorities to each classificatoin type, Etc. Values represent the significant of this classification. Examples could be 3, 5, 1, Etc. Note: dont use 0! Default if not completed is 1.
    </div>    
    <div class="control-group">
      <%= f.submit 'Create Asset Type', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', businessunits_path , :class => "pure-button pure-button-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/businessunits/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/businessunits/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Asset Classification</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">

                            <table class="table table-bordered">
                              <tr>
                                <th>Classification Type</th>
                                <th>Name</th>
                                <th>Classification Criteria</th>
                            </tr>

                            <% @businessunits.each do |businessunit| %>
                            <tr>
                                <td><%= businessunit.b_name %></td>
                                <td><%= businessunit.b_site %></td>
                                <td><%= businessunit.b_country %></td>
                                <td><%= link_to 'Show', businessunit %></td>
                                <td><%= link_to 'Destroy', businessunit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                            </tr>
                            <% end %>
                        </table>

                        <br />

                        <%= link_to 'New Asset', new_businessunit_path , :class => "pure-button pure-button-primary"  %>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/businessunits/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/businessunits/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

      <p>
        <b>Classification Type</b>
        <%= @businessunit.b_name %>
      </p>

      <p>
        <b>Name</b>
        <%= @businessunit.b_site %>
      </p>

      <p>
        <b>Type</b>
        <%= @businessunit.b_area %>
      </p>

      <p>
        <b>Classification Criteria</b>
        <%= @businessunit.b_city %>
      </p>

      <p>
        <b>Value</b>
        <%= @businessunit.b_state %>
      </p>


      <%= link_to "Create PDF", businessunit_path(@businessunit, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_businessunit_path(@businessunit) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New Asset Type', new_businessunit_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>