config/routes.rb
App::Application.routes.draw do

  resources :classifications

  resources :inventories

  resources :assets

  resources :analyses

  resources :labellings

  resources :businessunits
  resources :calendar
  devise_for :users
  resources :policies
  resources :dashboards

  root :to => 'dashboards#index'

end

app/models/classification.rb
class Classification < ActiveRecord::Base
  attr_accessible :a_type, :c_type, :criteria, :name, :value
  has_many :assets
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  # GET /classifications
  # GET /classifications.json
  def index
    @classifications = Classification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classifications }
    end
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
    @classification = Classification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classification }
      format.pdf do
        pdf = ClassificationsPdf.new(@classification)
        send_data pdf.render , filename: "#{@classification.c_type}.pdf", type: "application/pdf" , disposition: "inline"
      end
    end
  end

  # GET /classifications/new
  # GET /classifications/new.json
  def new
    @classification = Classification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classification }
    end
  end

  # GET /classifications/1/edit
  def edit
    @classification = Classification.find(params[:id])
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(params[:classification])

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'Classification was successfully created.' }
        format.json { render json: @classification, status: :created, location: @classification }
      else
        format.html { render action: "new" }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classifications/1
  # PUT /classifications/1.json
  def update
    @classification = Classification.find(params[:id])

    respond_to do |format|
      if @classification.update_attributes(params[:classification])
        format.html { redirect_to @classification, notice: 'Classification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification = Classification.find(params[:id])
    @classification.destroy

    respond_to do |format|
      format.html { redirect_to classifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| %>
  <% if @classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% @classification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span11 offset well">
  <div class="form-horizontal">

    <div class="control-group">
      <%= f.label 'Classification type'%><br />
    <%= f.text_field :c_type %><br>
      name a new type
    </div>
    <div class="control-group">
      <%= f.label :name %><br />
    <%= f.text_field :name %><br>
      You will need to create a name for your classification. Examples could be "High", "Low", etc.
    </div>
    <div class="control-group">
      <%= f.label :type %><br />
    <%= f.text_field :a_type %><br>
      Type of an asset. Examples: "Hardware, Software, Etc"
    </div>
    <div class="control-group">
      <%= f.label :criteria %><br />
    <%= f.text_field :criteria %><br>
      Very important. It's crucial when classifying to be consistent with the criteria you use to say a given asset is one or another type. Ideally your criteria should be simple and practical. Dont get too creative here. Examples: "The asset worth is higher than a 40k EUR", "The disclosure of this asset could mean legal actions against the company", Etc.
    </div>
    <div class="control-group">
      <%= f.label :value %><br />
    <%= f.number_field :value %><br>
      At a later stage of your classification (and Risk Management) this will be useful to give numerical priorities to each classificatoin type, Etc. Values represent the significant of this classification. Examples could be 3, 5, 1, Etc. Note: dont use 0! Default if not completed is 1.
    </div>    
    <div class="control-group">
      <%= f.submit 'Create Asset Type', :class => "pure-button pure-button-primary"%>
      <%= link_to 'Cancel', businessunits_path , :class => "pure-button pure-button-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/classifications/edit.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">
			<div class="span12 offset well">
				<%= render 'form' %>
			</div>
		</div>
	</div>
	<!-- 	<div id="footer">Footer</div> -->

</body>
</html>

app/views/classifications/index.html.erb
<html>
<head>
    <title></title>
</head>
<body>
    <div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
    <div id="main-wrap">
        <div id="sidebar">
            <%= render :partial => "layouts/menu" %>
        </div>
        <div id="content-wrap">
            <div class="sapn10 offset well">
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#Policy" data-toggle="tab">Asset Classification</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="Policy" class="tab-pane active">

                            <table class="table table-bordered">
                              <tr>
    <th>C type</th>
    <th>Name</th>
    <th>A type</th>
    <th>Criteria</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classifications.each do |classification| %>
  <tr>
    <td><%= classification.c_type %></td>
    <td><%= classification.name %></td>
    <td><%= classification.a_type %></td>
    <td><%= classification.criteria %></td>
    <td><%= classification.value %></td>
    <td><%= link_to 'Show', classification %></td>
    <td><%= link_to 'Edit', edit_classification_path(classification) %></td>
    <td><%= link_to 'Destroy', classification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

                        <br />

                        <%= link_to 'New Classification', new_classification_path , :class => "pure-button pure-button-primary"  %>
                    </div>
                </div><!-- /.tab-content -->
            </div><!-- /.tabbable -->
        </div>
    </div>
</div>
<!-- <div id="footer">Footer</div> -->
</body>
</html>





<h1>Listing classifications</h1>

<table>
  <tr>
    <th>Classification type</th>
    <th>Name</th>
    <th>Type</th>
    <th>Criteria</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classifications.each do |classification| %>
  <tr>
    <td><%= classification.c_type %></td>
    <td><%= classification.name %></td>
    <td><%= classification.a_type %></td>
    <td><%= classification.criteria %></td>
    <td><%= classification.value %></td>
    <td><%= link_to 'Show', classification %></td>
    <td><%= link_to 'Edit', edit_classification_path(classification) %></td>
    <td><%= link_to 'Destroy', classification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classification', new_classification_path %>

app/views/classifications/new.html.erb
<html>
<head>
	<title></title>
</head>
<body>
	<div id="header">
        <div><img src="/images/fixnix.png"></div>
    </div>
	<div id="main-wrap">
		<div id="sidebar">
			<%= render :partial => "layouts/menu" %>
		</div>
		<div id="content-wrap">

			<%= render 'form' %>
			<br>

		</div>
	</div>
	<!-- <div id="footer">Footer</div> -->
</body>
</html>

app/views/classifications/show.html.erb
<html>
<head>
  <title></title>
</head>
<body>
  <div id="header">
    <div><img src="/images/fixnix.png"></div>
  </div>
  <div id="main-wrap">
    <div id="sidebar">
      <%= render :partial => "layouts/menu" %>
    </div>
    <div id="content-wrap">
      <p id="notice"><%= notice %></p>

      <p>
  <b>Classification Type:</b>
  <%= @classification.c_type %>
</p>

<p>
  <b>Name:</b>
  <%= @classification.name %>
</p>

<p>
  <b>Asset type:</b>
  <%= @classification.a_type %>
</p>

<p>
  <b>Criteria:</b>
  <%= @classification.criteria %>
</p>

<p>
  <b>Value:</b>
  <%= @classification.value %>
</p>


      <%= link_to "Create PDF", classification_path(@classification, :format => "pdf") , :class => "pure-button pure-button-primary"  %>
      <%= link_to 'Edit', edit_classification_path(@classification) , :class => "pure-button pure-button-primary" %> 
      <!--      <%= link_to 'Back', businessunits_path , :class => "pure-button pure-button-primary" %> -->

      <%= link_to 'New Asset Type', new_classification_path , :class => "pure-button pure-button-primary"  %>

    </div>
  </div>
  <!--   <div id="footer">Footer</div> -->

</body>
</html>